login and bloghome page
bellatrixdatacommunity/lets-blog pull request #4
Opened 2020-06-13 16:49 UTC by Nikhil22404

I have made login page and blog homepage(with headder and footer)

2020-06-16 15:25 UTC, ramanaditya requested changes
Use this folder structure to add your files
- lets_blog/
  |- static/
  |     |- CSS/
  |     |     |- Put your css files
  |     |- js/
  |     |     |- Put your js files
  |     |- images
  |           |- Put your images here
  |- templates/
  |     |- put your HTML files here

Before this, take a pull request, from this repo to yours, save the changes and make a PR again

CC: @Nikhil22404

2020-06-16 16:39 UTC, Nikhil22404 commented
How to create a pull request from that repo to mine repo?

On Tue, 16 Jun, 2020, 8:55 PM Aditya Raman, <notifications@github.com>
wrote:

> *@ramanaditya* requested changes on this pull request.
>
> Use this folder structure to add your files
>
>    - lets_blog/
>    |- static/
>    | |- CSS/
>    | | |- Put your css files
>    | |- js/
>    | | |- Put your js files
>    | |- images
>    | |- Put your images here
>    |- templates/
>    | |- put your HTML files here
>
> Before this, take a pull request, from this repo to yours, save the
> changes and make a PR again
>
> CC: @Nikhil22404 <https://github.com/Nikhil22404>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bellatrixdatacommunity/lets-blog/pull/4#pullrequestreview-431626819>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANYCJNWIERNWWL2E6XB4KKLRW6FHRANCNFSM4N5B273Q>
> .
>

2020-06-16 16:40 UTC, Nikhil22404 commented
I am beginner to git and GitHub so..

On Tue, 16 Jun, 2020, 10:09 PM Nikhil Naik, <naiknikhil925@gmail.com> wrote:

> How to create a pull request from that repo to mine repo?
>
> On Tue, 16 Jun, 2020, 8:55 PM Aditya Raman, <notifications@github.com>
> wrote:
>
>> *@ramanaditya* requested changes on this pull request.
>>
>> Use this folder structure to add your files
>>
>>    - lets_blog/
>>    |- static/
>>    | |- CSS/
>>    | | |- Put your css files
>>    | |- js/
>>    | | |- Put your js files
>>    | |- images
>>    | |- Put your images here
>>    |- templates/
>>    | |- put your HTML files here
>>
>> Before this, take a pull request, from this repo to yours, save the
>> changes and make a PR again
>>
>> CC: @Nikhil22404 <https://github.com/Nikhil22404>
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/bellatrixdatacommunity/lets-blog/pull/4#pullrequestreview-431626819>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ANYCJNWIERNWWL2E6XB4KKLRW6FHRANCNFSM4N5B273Q>
>> .
>>
>

2020-06-19 07:37 UTC, ramanaditya approved these changes

2020-06-19 07:38 UTC, merged